"""add is_active to products

Revision ID: e68b454e4510
Revises: 75ef7c539dd0
Create Date: 2026-08-19 11:03:49.074563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68b454e4510'
down_revision: Union[str, Sequence[str], None] = '75ef7c539dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
